<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Select</name>
   <tag></tag>
   <elementGuidId>3da342ea-49c2-4f47-b8da-87f0b7a880e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.chakra-button.css-ez23ye</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8722e544-d2ee-4c8f-9f57-7e038a432f51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6d0cfce1-130b-4c63-b845-a90c1aee6bd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-button css-ez23ye</value>
      <webElementGuid>adf8c7ad-8f49-4ea9-a4df-6745d9f62883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>f29fd793-4be0-4792-9171-6b81842b9533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;row styles_mainLayoutContainer__cBnGy&quot;]/div[@class=&quot;styles_mainContentWrapper__rdtpQ col-xs-12&quot;]/div[@class=&quot;row styles_mainContentContainer__VAvSS&quot;]/div[@class=&quot;styles_contentContainer__bBYPw col-xs-custom&quot;]/div[@class=&quot;styles_box_1__7OoH2&quot;]/div[@class=&quot;styles_teammatesContainer__M3wle&quot;]/div[@class=&quot;chakra-container styles_containerStyle__RhBz_ css-1yk2h4k&quot;]/div[@class=&quot;chakra-wrap css-0&quot;]/ul[@class=&quot;chakra-wrap__list css-19lo6pj&quot;]/label[@class=&quot;chakra-wrap__listitem css-1yp4ln&quot;]/div[@class=&quot;css-knvckk&quot;]/div[1]/div[@class=&quot;chakra-card styles_ProjectTeamCard__K5R_f css-jv498s&quot;]/div[@class=&quot;chakra-card__body css-1idwstw&quot;]/button[@class=&quot;chakra-button css-ez23ye&quot;]</value>
      <webElementGuid>e7b97913-d409-4664-9374-9f5c233a0dff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>978c8063-e068-4830-9d9c-fb5404e4d05c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div/div[2]/div/div[2]/div/ul/label/div/div/div/div/button</value>
      <webElementGuid>010317a5-924c-4cf8-89bb-537bb2adc798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Learn about HatchWorks', &quot;'&quot;, ' roles')])[1]/following::button[1]</value>
      <webElementGuid>32ade3d1-9dda-416f-b22e-6aac51d6668d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Let', &quot;'&quot;, 's build your team')])[1]/following::button[2]</value>
      <webElementGuid>ff37a831-33f5-4e63-a0a3-af668d825197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select'])[2]/preceding::button[1]</value>
      <webElementGuid>4c4270eb-3c31-4eeb-800c-6f6d12a75dc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select'])[3]/preceding::button[2]</value>
      <webElementGuid>98ba503b-610a-4f2d-b3a9-aefd308850f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select']/parent::*</value>
      <webElementGuid>ddb7b391-387f-4641-ba17-b7e3dc2c52b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div/div/div/div/button</value>
      <webElementGuid>49736e1a-d778-49e8-bf1d-8f8168958abc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>8cd96375-c097-441a-bbe7-3c292d340470</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
