<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_</name>
   <tag></tag>
   <elementGuidId>a022bc5f-b60e-40ff-b9e5-1787b4051149</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5f507c0a-7fa3-4f17-aba2-26fc04487778</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3b052849-8de4-42f5-9163-c3109d88abd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-button styles_qtyButtonStyle__dsc07 css-ez23ye</value>
      <webElementGuid>91176785-3459-4243-9339-b2f262032246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5592675f-3e83-4877-9546-14d79a3cda25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>3444c94a-e5ef-4217-9300-4a4cfa7dbe72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+</value>
      <webElementGuid>2368bf99-55df-4de8-b7a6-00387cc303cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;row styles_mainLayoutContainer__cBnGy&quot;]/div[@class=&quot;styles_mainContentWrapper__rdtpQ col-xs-12&quot;]/div[@class=&quot;row styles_mainContentContainer__VAvSS&quot;]/div[@class=&quot;styles_contentContainer__bBYPw col-xs-custom&quot;]/div[@class=&quot;styles_box_1__7OoH2&quot;]/div[@class=&quot;styles_teammatesContainer__M3wle&quot;]/div[@class=&quot;chakra-stack css-tl3ftk&quot;]/div[@class=&quot;styles_boxAddTeammate__ddEO6 css-0&quot;]/div[@class=&quot;styles_containerStyle__4MMn6 css-0&quot;]/div[@class=&quot;chakra-wrap css-0&quot;]/ul[@class=&quot;chakra-wrap__list css-19lo6pj&quot;]/label[@class=&quot;chakra-wrap__listitem css-1yp4ln&quot;]/div[@class=&quot;css-knvckk&quot;]/div[@class=&quot;styles_seniorCardContainer__nAnDG&quot;]/div[@class=&quot;chakra-card styles_ProjectSeniorCard__ath7_ css-jv498s&quot;]/div[@class=&quot;chakra-card__body css-1idwstw&quot;]/div[@class=&quot;styles_qtyFlexStyle__5Ts2q css-k008qs&quot;]/button[@class=&quot;chakra-button styles_qtyButtonStyle__dsc07 css-ez23ye&quot;]</value>
      <webElementGuid>718b97f9-15bf-4df3-a0d5-e1f3d3fe113c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>529b6300-3299-4bf8-a4c7-6f147314b8b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div/div[2]/div/div[2]/div/div/div[2]/ul/label/div/div/div/div/div[2]/button[2]</value>
      <webElementGuid>54d7ac5b-e23f-4f91-b105-04fe9b0fb7fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/following::button[1]</value>
      <webElementGuid>88f20002-48e2-4f6f-85bf-d7bd4f5efb6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Learn about HatchWorks', &quot;'&quot;, ' roles')])[1]/following::button[3]</value>
      <webElementGuid>bfc950d9-b27b-4f4f-a039-56acc2fa31b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[2]/preceding::button[1]</value>
      <webElementGuid>887f2b74-ce81-4a07-8710-b4a0e9b579d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[2]/preceding::button[2]</value>
      <webElementGuid>ef7b292b-6ad3-41b9-abb7-76eb2eb97736</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='+']/parent::*</value>
      <webElementGuid>30ba4277-f73c-4322-bbd7-00ac803dcbec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>05fb5387-caf3-4ea1-8ab8-5a9679f607b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '+' or . = '+')]</value>
      <webElementGuid>7141ec0f-3a98-4f62-80cc-b6d06f44a253</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
